# Generated by Django 2.2.6 on 2019-12-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='list',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
