# Generated by Django 2.2.6 on 2019-12-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20191206_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
